### ISSUE TITLE
./cook: line 286: /bin/mv: Argument list too long

### ISSUE THREAD

**Issue by coryarcangel** [coryarcangel/Cookery#14]
rm on 44110 file is too many commands for Bash. Maybe this is better? https://stackoverflow.com/questions/11289551/argument-list-too-long-error-for-rm-cp-mv-commands

**Comment by coryarcangel** [comment]
@hvandusen Checking on this, thx Henry!

**Comment by hvandusen** [comment]
Fixed! LMK if you have any more trouble!

**Comment by hvandusen** [comment]
optimistically closing 🫡

**Comment by coryarcangel** [comment]
Been working for me!
